# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
#orbs:
  # Declare a dependency on the welcome-orb
#  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  createInventory:
    docker:
      - image: amazon/aws-cli
    steps: 
      - run: pwd
      #- run: aws cloudformation create-stack --stack-name udacity-module3-infra --template-body file://../template.yml --parameters ParameterKey=$AWS_ACCESS_KEY_ID, ParameterKey=AWS_SECRET_ACCESS_KEY, ParameterKey=AWS_DEFAULT_REGION
      #- run: echo [all] > ~/inventory
      #- run:
      #    name: " list and append the ec2 instances to inventory "
      #    command: |
      #      aws ec2 describe-instances
      #      --query 'Reservations[*].Instances[*].PublicIpAddress'
      #      --filters "Name=tag:Project,Values=udacity"
      #      --output text >> ~/inventory
      #-  persist_to_workspace:
      #     root: ~/
      #     paths:
      #       - .
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - createInventory
